language: node_js
node_js:
- '0.10.25'
before_script:
- npm install -g grunt-cli
- npm install
script:
- grunt prod
after_success:
- chmod -R 777 .travis-build.sh
- ./.travis-build.sh
env:
  global:
    secure: BZTQ48vcf8TKhtRm1TUYYrAVD5i5MvDyEgA8r3YTXuimi9Swv6rSNcS24ZEB+Z4eWjDr30VC3LEqM/t0dtQH+wKXWiHSohH/ssHUL+Z0WPYptlR7+KZluCDks18wU5CWRFm+gp6gR4tbsKZT4DZNNMWqrmFQslL6GcjPwgOLR4E=
